### ISSUE TITLE
Upgrade for Blender 2.80

### ISSUE THREAD

**Issue by emackey** [AlansCodeLog/blender-debugger-for-vscode#11]
Can this addon be updated for Blender 2.80?

Amazing work here, BTW.

**Comment by alanscodelog** [comment]
I actually just pushed a branch today [`update-to-2.8`](https://github.com/AlansCodeLog/blender-debugger-for-vscode/tree/update-to-2.8) that has the minimal changes needed for it to work with 2.8, but I will not be officially releasing it until 2.8 is officially released.

It should work, if not, do feel free to open an issue, but I wanted to see, if I had some time during/after the holidays, if I could redo some parts to make the whole process more automatic and add some features.

**Comment by Dene33** [comment]
I think you should really stick to 2.79b version, because there is already 2.8 implementation - https://github.com/JacquesLucke/blender_vscode And author will not port it to 2.79.

**Comment by emackey** [comment]
The 2.8 branch here is working fine for me, FYI.  I've been using it to debug the glTF import/export plugin.

**Comment by alanscodelog** [comment]
@Dene33 Yes, I'm aware of blender_vscode, but mine also technically supports Visual Studio and is flexible in what ptvsd version it will take. So it will be updated to 2.8.

Whatever happens, I will fix any bugs that might come up for the 2.79 version. But I will try and see if some of the features I wanted to try adding, can be added to both. Many things I want to try are not tied down to a specific blender API version, so they would work whether the addon is 2.79 or 2.8. If you look at the changes that I had to make to update it to 2.8 they are minor (3 lines I think). 

I can't guarantee any new features or even the rewrite, but if it happens, I will make things more modular, so most features will work regardless of the blender version, both for backwards compatibility and to make future changes easy.

If I have time, another option is to fork, or write something similar to blender_vscode, so that instead of injecting some behind the scenes magic, it injects my addon which would then install pip and provide a server for commands (reload addon, etc). This would also nicely fixes this [feature request](https://github.com/JacquesLucke/blender_vscode/issues/8) for blender_vscode, and would provide a clean uninstall from Blender's side, which as far as I know, blender_vscode doesn't. All the while maintaining compatibility with Visual Studio.

**Comment by gerroon** [comment]
I get an error with this line

```
from bpy.types import Operator
```

```
Exception has occurred: SyntaxError
non-default argument follows default argument (types.py, line 21654)
  File "C:\DEV\dev_blender28\ADDON\testing_2.py", line 27, in <module>
    from bpy.types import Operator

```

Blender 2.8 does not seem to complaint about it, but the debugger does inside Vscode

**Comment by alanscodelog** [comment]
@gerroon Could not reproduce. Works fine for me. If you can reproduce it with a minimal example please file a separate issue with the details and be sure to fill out exactly which blender 2.8 version you're using.

Also that error is weird since it has to do with default arguments in functions not imports afaik. Is `from bpy.types import Operator` on line 27? or is it at the start of the file?

**Comment by emackey** [comment]
@AlansCodeLog Thanks for this awesome debugging tool!

In the latest Blender 2.80 builds, I'm seeing this when I launch the debug server:

```
Traceback (most recent call last):
  File "..\blender-2.80.0-git.ce3475f74794-windows64\2.80\scripts\addons\blender-debugger-for-vscode\__init__.py", line 169, in execute
    prefs = bpy.context.user_preferences.addons[__name__].preferences
AttributeError: 'Context' object has no attribute 'user_preferences'
```

Maybe the API has changed?

**Comment by alanscodelog** [comment]
@emackey Thanks, yes, it seems it has been changed to just `preferences` instead of `user_preferences`.

I've been working on the update but I hadn't noticed yet because I had been working on making this load in both 2.79 and 2.80 without users having to change the bl_info. It seems to be working! Checking all the APIs work is the next step. I will push to the branch when that's done. I need to do some cleanup first, the code is a bit of mess at the moment.

**Comment by pjoe** [comment]
Just wanted to add that it seems to work just fine with latest 2.80 (that I build locally today)

Very nice work 👍 

One small note, if others run into similar thing: I've been using symlinks (on Windows) to link git checkouts of addons into my user script dir, however that doesn't seem to work with the VSC debugger (probably because paths then look different from blender/vscode). My solution was to add the addon folders to blender's script setting and everything works.

**Comment by RSoul82** [comment]
This looks like a useful addon, but after installing it's not showing up in the addons list in preferences. The files do get extracted to my addons folder.

**Comment by alanscodelog** [comment]
@RSoul82 Did you download it from the releases and install it directly? This fails silently. Please read the release notes. Otherwise please open a new issue with all the relevant details.

**Comment by IamKraZ** [comment]
AlansCodeLog - I'm running to 2.8 release, I added it in the addons but it doesn't show up in the search (spacebar) in blender. It shows in Addons BTW. 

Any ideas?

Edit:
and if I can't get it to work in Blender I definitely can't get it to work in VSC.

**Comment by emackey** [comment]
Now that Blender 2.80 stable has been out a while, maybe this branch can be merged to master?

**Comment by alanscodelog** [comment]
@emackey Done. Sorry it took so long I've been very busy.

@IamKraZ  It's working for me. Please check with the latest release and open a new issue if it's not working.
